CruGlobal/mobile-content-api

- app/controllers/resources_controller.rb
- db/seeds.rb
- spec/controllers/resources_controller_spec.rb
1. Don't include any translations unless specified
2. Include translations with all resources
> Include translations

- app/models/resource.rb
- db/migrate/20170414034911_one_sky_not_required.rb
- db/schema.rb
- spec/controllers/resources_controller_spec.rb
Remove not_null on OneSky project ID since not all projects will necessarily need translation
> Remove not_null on OneSky project ID

- app/controllers/auth_controller.rb
- app/controllers/secure_controller.rb
- app/models/access_code.rb
- app/models/auth_token.rb
- app/serializers/auth_token_serializer.rb
- db/migrate/20170503210608_expire_codes_and_tokens.rb
- db/migrate/20170504142441_unique_codes_and_tokens.rb
- db/schema.rb
- spec/acceptance/auth_controller_spec.rb
- spec/controllers/secure_controller_spec.rb
- spec/models/access_code_spec.rb
- spec/models/auth_token_spec.rb
Add expirations of 1 day to auth tokens and 1 week to access codes.  A little background: a user creates an auth token via a valid access code.
> Expiration

- public/xmlns/content.xsd
- public/xmlns/tract.xsd
sample xml:
```xml
<button
type="event"
value="event1 followup:send" />
```
```xml
<link
events="event1 followup:send" />
```
```xml
<call-to-action
events="event1 kgp:circles" />
```
> Schema: call-to-action event attribute should be a list of event ids

- public/xmlns/content.xsd
Document what the default behavior for color of buttons is. Also add a color attribute to support overriding the default color behavior.
Sample XML:
```xml
<content:button
color="rgba(255,0,0,1)" />
```
> Button color attribute & default behavior documentation

- Gemfile
- Gemfile.lock
- app/controllers/application_controller.rb
- app/controllers/follow_ups_controller.rb
- app/models/destination.rb
- app/models/error/bad_request_error.rb
- app/models/follow_up.rb
- config/routes.rb
- db/migrate/20170606210728_follow_up_destination.rb
- db/schema.rb
- db/seeds.rb
- spec/acceptance/drafts_controller_spec.rb
- spec/acceptance/follow_ups_controller_spec.rb
- spec/models/auth_token_spec.rb
- spec/models/follow_up_spec.rb
- spec/page_util_spec.rb
- spec/spec_helper.rb
Here's what I have so far, what do you think @ryancarlson ?
> GT 324/325

- public/xmlns/content.xsd
This has no functional changes, just cleaning up some unused validation code.
> remove unnecessary fullAlignValue type

- public/xmlns/content.xsd
Just documenting the already existing behavior.
> document defaults for the text-align attribute

- public/xmlns/content.xsd
- public/xmlns/tract.xsd
Sample XML:
```xml
<card dismiss-listeners="followup-not-ready" />
```
> Card dismiss-listeners

- db/seeds.rb
- public/xmlns/content.xsd
- public/xmlns/tract.xsd
- spec/models/page_spec.rb
- spec/page_util_spec.rb
moved paragraph, form, and tabs to content schema
> Content elements

- app/controllers/custom_pages_controller.rb
- app/models/custom_page.rb
- app/models/language.rb
- app/models/translation.rb
- app/serializers/custom_page_serializer.rb
- app/serializers/language_serializer.rb
- app/serializers/translation_serializer.rb
- db/migrate/20170705200338_custom_pages_child_of_language.rb
- db/migrate/20170705203601_language_id_not_null.rb
- db/schema.rb
- db/seeds.rb
- spec/acceptance/custom_pages_controller_spec.rb
- spec/models/custom_page_spec.rb
- spec/models/translation_spec.rb
I will merge this once #97 has been merged and the data updated
> Language id not null

- app/controllers/languages_controller.rb
- spec/acceptance/custom_pages_controller_spec.rb
- spec/acceptance/drafts_controller_spec.rb
- spec/acceptance/follow_ups_controller_spec.rb
- spec/acceptance/languages_controller_spec.rb
- spec/acceptance/pages_controller_spec.rb
1. Handle duplicate language error
2. Fix some tests
> Language error

- app/models/resource.rb
- app/serializers/resource_serializer.rb
- spec/models/resource_spec.rb
@frett do you have any problems with this?
> Show latest draft or translation

- app/controllers/application_controller.rb
- spec/controllers/application_controller_spec.rb
I ran into this with a DELETE request.
> Don't merge parameters if body is nil

- .rubocop.yml
- app/models/translation.rb
- app/serializers/translation_serializer.rb
- db/migrate/20180410112406_add_tagline_to_translations.rb
- db/schema.rb
- spec/models/translation_spec.rb
A new field from name_description.xml for display on app home screen with each tool.
> Add tagline

- app/models/follow_up.rb
- spec/models/follow_up_spec.rb
> utilize Hash.to_query to correctly escape query params

- public/xmlns/manifest.xsd
no functional changes, just documentation of expected behavior
> document the primary-color, primary-text-color, and text-color attributes

- public/xmlns/article.xsd
- public/xmlns/manifest.xsd
Sample XML:
```xml
<manifest xmlns="https://mobile-content-api.cru.org/xmlns/manifest" 
xmlns:article="https://mobile-content-api.cru.org/xmlns/article" 
xmlns:content="https://mobile-content-api.cru.org/xmlns/content"
category-label-color="rgba(255,255,255,1)">
<categories>
<category id="about-god" banner="about-god.jpg">
<label>
<content:text>About God</content:text>
</label>
<article:aem-tag id="faith-topics:attributes-of-god/god-never-changes" />
<article:aem-tag id="faith-topics:share-your-faith/testimony" />
</category>
</categories>
</manifest>
```
> Article categories XML Schema

- public/xmlns/manifest.xsd
- public/xmlns/tract.xsd
> document the default background colors for manifest and tract pages

- app/lib/one_sky.rb
- app/lib/page_client.rb
- app/models/translation.rb
- app/models/xml/manifest.rb
- app/models/xml/translatable.rb
- spec/models/xml/manifest_spec.rb
- spec/package_spec.rb
https://jira.cru.org/browse/GT-517
there's some open questions that I do have (will try to point them with code comments).
when some of those assumptions change or more cleanup is preferred this will need more work.
also did a bit of refactoring as I was absorbing code into my brain (happy to revert as/if needed).
> GT-517:  Allow manifests to be processed for OneSky translations

- app/lib/one_sky.rb
- spec/models/translation_spec.rb
as noted here: https://github.com/CruGlobal/mobile-content-api/pull/177#discussion_r305899536
> do not raise when OneSky returns no content

- .travis.yml
we started hitting CI failures (since yesterday) due unable to connect to the Postgres data source
> [ci] explicitly declare postgresql service

- Gemfile
- Gemfile.lock
also do not declare transitive gems the app does not need to ...
closes #193
> drop unused dependencies

- public/xmlns/analytics.xsd
This updates the list of support analytics systems in content xml
> Analytics systems update

- config/puma.rb
> Extra change for rails upgrade

- spec/rails_helper.rb
docs: https://github.com/simplecov-ruby/simplecov#filters
This should drop coverage percentage to about 95.83%
> fix code coverage reporting

- app/controllers/custom_tips_controller.rb
- spec/acceptance/custom_tips_controller_spec.rb
- spec/acceptance/tips_controller_spec.rb
- spec/factories/custom_tips.rb
- spec/factories/tips.rb
I wrote tests for the controller and got the same error that @frett was experiencing. I then fixed it exactly the way he thought we needed to. (maybe he should take over for me 😉)
See convo in previous PR: https://github.com/CruGlobal/mobile-content-api/pull/435#discussion_r458413836
> GT-933 - Fix custom tip update

- app/models/attachment.rb
Lottie animations are distributed as json files, this will allow the API to accept Lottie animations as uploads which will then be used to include animations within tools.
> GT-997 support uploading lottie animation json

- app/lib/package.rb
- public/xmlns/content.xsd
Sample XML:
```xml
<content:animation
resource="34678-android-or-apple.json" 
events="toggleAnimation" 
play-listeners="toggleAnimation playAnimation" 
stop-listeners="toggleAnimation stopAnimation" />
<content:animation
resource="34678-android-or-apple.json" 
autoplay="false"
loop="false"
events="toggleAnimation" 
play-listeners="toggleAnimation playAnimation" 
stop-listeners="toggleAnimation stopAnimation" />
```
> GT-977 Support defining animations in the content xml

- app/lib/xml_util.rb
https://rollbar.com/Cru/mobile-content-api/items/207/
> specify the xml namespaces when evaluating the translatable_nodes xpath expression

- .travis.yml
- public/xmlns/content.xsd
- public/xmlns/lesson.xsd
- schema_tests/lesson/valid/tests/spacers.xml
This is currently just a proof-of-concept to allow layout testing to be performed in the stage environment
> add support for a spacer element

- public/xmlns/content.xsd
- schema_tests/tract/invalid/tests/tabs_no_tabs.xml
- schema_tests/tract/invalid/tests/tabs_too_many_tabs.xml
Sample XML:
```xml
<content:accordion>
<content:section>
<content:header><content:text>Sentence 1: Describe the occasion, the problem, and identify a theme.</content:text></content:header>
<content:text>“Last week I was having a conflict with a co-worker that caused me lots of anxiety.”</content:text>
</content:section>
<content:section>
<content:header><content:text>Sentence 2: Explain how Jesus made a difference in the situation.</content:text></content:header>
<content:text>“Then on Sunday the pastor shared a Bible verse about how Jesus helps us carry our burdens. It really clicked with me that I no longer have to carry my anxiety alone.”</content:text>
<content:image ref="illustration.jpg" />
</content:section>
</content:accordion>
```
> GT-1027 Accordion content element

- public/xmlns/lesson.xsd
Allow lesson pages to be marked as hidden and for listeners to be defined for a lesson page
> GT-1080 GT-1103 add support for listeners and hidden lesson pages

- config/initializers/ddtrace.rb
"modern" = what all the other apps are doing
> Use more modern datadog config

- public/xmlns/tract.xsd
- Include some missing default styles for modals
- allow modals to specify a text-scale
> Allow a text-scale to be set on a Modal

- public/xmlns/content.xsd
- schema_tests/lesson/valid/tests/multiselect.xml
```xml
<content:multiselect state="quiz2" columns="4">
<content:option value="a">
<analytics:event system="firebase">
<analytics:attribute key="key" value="value" />
</analytics:event>
<content:text>Test</content:text>
<content:image resource="test.png" />
</content:option>
</content:multiselect>
```
> GT-1272 support defining analytics events on multiselect options

- .github/workflows/xml-schema-validation.yml
- public/xmlns/cyoa.xsd
- public/xmlns/manifest.xsd
- public/xmlns/page_cardcollection.xsd
- public/xmlns/page_content.xsd
- schema_tests/cyoa/valid/tests/page_cardcollection.xml
- schema_tests/cyoa/valid/tests/page_content.xml
- schema_tests/lesson/invalid/tests/page_cardcollection.xml
- schema_tests/lesson/invalid/tests/page_content.xml
This PR defines the content and cardcollection page types for Choose Your Own Adventure tools
> GT-1294 Choose Your Own Adventure tool type

- public/xmlns/content.xsd
- public/xmlns/manifest.xsd
- public/xmlns/tract.xsd
- schema_tests/manifest/valid/tools/satisfied.xml
Sample xml:
```xml
<content:card>
<content:image />
<content:text>You can have any number of elements within a Card</content:text>
</content:card>
<content:card events="do_something">
<content:text>Cards can be made clickable to trigger content events that other elements can listen for</content:text>
</content:card>
<content:card url="https://www.example.com">
<content:text>Cards can be made clickable to open a URL</content:text>
</content:card>
<content:card background-color="rgba(200,200,200,1)">
<content:text>Cards can have custom background colors defined</content:text>
</content:card>
```
> GT-1338 Create a card content element

- public/xmlns/content.xsd
- record current platform support for features
- remove flow feature until we need to actually define flow fallback behavior
> Cleanup spec features

- public/xmlns/page_cardcollection.xsd
- schema_tests/cyoa/valid/tests/page_cardcollection.xml
- add analytics events to cards on the card collection page type
- add support for defining a background-color for cards
> GT-1294 Update the spec for card collection pages

- public/xmlns/content.xsd
This will allow us to dynamically hide/show flow items
Sample XML:
```xml
<content:flow>
<content:item gone-if="!isSet(var)">
<content:image resource="emoji.png" />
</content:item>
</content:flow>
```
> GT-1403 Support state visibility for flow items

- public/xmlns/analytics.xsd
this will be used to track events within tools in our User Counters framework
> GT-1382 Support the "user" analytics system

- public/xmlns/content.xsd
This will allow us to use a different style for the emoji survey vs lessons
> GT-1404 Support a flat style for Multiselect options

- app/lib/package.rb
- app/lib/xml_util.rb
- public/xmlns/content.xsd
- public/xmlns/cyoa.xsd
- public/xmlns/manifest.xsd
- public/xmlns/page.xsd
- public/xmlns/page_cardcollection.xsd
- public/xmlns/shareable.xsd
- schema_tests/manifest/invalid/tests/sharables_duplicate_id.xml
- schema_tests/manifest/valid/tests/sharables.xml
Sample XML:
```xml
<manifest xmlns="https://mobile-content-api.cru.org/xmlns/manifest" xmlns:content="https://mobile-content-api.cru.org/xmlns/content">
<items xmlns="https://mobile-content-api.cru.org/xmlns/shareable">
<image id="shareable1" resource="shareable1.png">
<description><content:text>Description of Shareable</content:text></description>
</image>
</items>
</manifest>
```
> GT-1436 Create Shareables XML schema

- Gemfile.lock
Not sure why dependabot decided it couldn't open a PR for this.
> Update rack (security update)

- .github/workflows/ruby.yml
Reverts CruGlobal/mobile-content-api#1387
> Revert "Update codecov/codecov-action action to v4"

- .github/workflows/ruby.yml
...because at the moment there are two: https://github.com/CruGlobal/cru-terraform/pull/4634/files
> [no-jira] Get CVE ignores via Action var

- app/serializers/user_serializer.rb
- simplify how given & family names are serialized
- expose the user's email via the user API
> User Serializer adjustments

- app/serializers/resource_serializer.rb
- spec/acceptance/resources_controller_spec.rb
- filter arbitrary resource_attributes based upon the fields parameter
- make the resource serializer keys symbols to correctly handle them with the fields parameter
> GT-2143 Fix fields parameter for resource serializer

- public/xmlns/content.xsd
- public/xmlns/manifest.xsd
- public/xmlns/page.xsd
- public/xmlns/tract.xsd
This PR better defines how events and listeners interact with each other and explicitly states when various listeners are "active"
> GT-2289 Better define how multiple events and listeners interact with each other

- Dockerfile
- config/environments/production.rb
- config/initializers/sync_secure_google_creds.rb
@frett I have no idea how I missed it (since I normally check to make sure that things deploy successfully), but it appears that the Rails 7 upgrade never made it to staging cause of a Dockerfile issue.
This PR fixes that, so maybe check staging again now that it's *actually* out there before I merge this?
Sorry about that!
> No need for assets for dockerfile
