app/controllers/translations_controller.rb
To allow clients to download list of translations, filtered by is_published for now, and include other things that it cares about.
=> Add index endpoint to translations controller

app/models/attribute.rb, app/models/resource.rb, app/serializers/resource_serializer.rb, db/seeds.rb, spec/acceptance/resources_controller_spec.rb, spec/models/attributes_spec.rb
1. Show resource attributes as attributes instead of a relationship
2. Force attribute keys to be in format blah_blah_blah
=> Attributes

manifest/content.xml, manifest/manifest.xml, manifest/tract.xml
This will allow page xml to be a bit more readable and not require rewriting resources when publishing.
This also provides a quick list of all resources used within a tool.
=> provide resource dereferencing via the manifest xml

public/xmlns/content.xsd, public/xmlns/tract.xsd
The purpose of this change is to be able to listen for multiple events for the same object. This allows us to name our events based on their source and not the target listener. This means we may have multiple buttons/events that end up at the same listener, but they will show up as distinct events within Google Analytics.
listeners are defined as a space separated list of event names.
I also added dismiss-listeners for modals to the tract schema
Sample xml:
```xml
<page
listeners="post-followup circles" />
```
```xml
<card
listeners="new-followup followup" />
```
```xml
<modal
listeners="followup-modal event2"
dismiss-listeners="dismiss-followup-modal event3" />
```
=> Schema: Update listener to be listeners

public/xmlns/content.xsd, public/xmlns/manifest.xsd, public/xmlns/tract.xsd
sample xml:
```xml
<manifest
background-image="image.png"
background-image-align="bottom start"
background-image-scale-type="fit" />
```
```xml
<page
background-image="image.png"
background-image-align="bottom"
background-image-scale-type="fill-x" />
```
```xml
<card
background-image="image.png"
background-image-align="center"
background-image-scale-type="fill-x" />
```
=> Image scale type and align

public/xmlns/content.xsd
This should simplifying some parsing logic, and doesn't overload the meaning of the value attribute
Sample XML:
```xml
<content:button
type="url"
url="https://www.google.com/" />
```
```xml
<content:button
type="event"
events="trigger-modal" />
```
=> separate button value attribute into distinct url and events attributes.

public/xmlns/manifest.xsd, public/xmlns/tract.xsd
This PR adds card-background-color and card-text-color attributes
Sample new XML:
```xml
<manifest
xmlns:tract="https://mobile-content-api.cru.org/xmlns/tract"
tract:card-background-color="rgba(255,255,255,1)" />
```
```xml
<page
card-background-color="rgba(255,255,255,1)"
card-text-color="rgba(90,90,90,1)" />
```
```xml
<card
text-color="rgba(90,90,90,1)" />
```
=> Card colors

app/models/resource.rb
I'm pretty sure this is the culprit
=> disable pushing translations to one sky when we create the first draft of a new language

app/models/translation.rb, db/seeds.rb, lib/xml_util.rb, public/xmlns/content.xsd, spec/models/translation_spec.rb
It searches through the document for all attributes that contain "-i18n-id" in its name, then returns the attributes, search in OneSky by the value, and replace the value with the result, and the name by removing "-i18n-id" from it.
=> GT-360: Support i18n-id replacement for attribute nodes 

public/xmlns/content.xsd
namespaces for events default to the tool code for the tool containing them. with the addition of "kgp-us" this should be widened to technically support that code as a namespace.
=> widen acceptable event namespaces to include - and _

app/controllers/application_controller.rb, app/controllers/attachments_controller.rb, app/controllers/attributes_controller.rb, app/controllers/custom_pages_controller.rb, app/controllers/follow_ups_controller.rb, app/controllers/languages_controller.rb, app/controllers/resources_controller.rb, app/controllers/translated_attributes_controller.rb, app/controllers/translated_pages_controller.rb, app/controllers/views_controller.rb, app/models/follow_up.rb, db/migrate/20170919235321_store_follow_ups.rb, db/schema.rb, spec/models/follow_up_spec.rb
I decided this would be a good idea after this: https://rollbar.com/Cru/mobile-content-api/items/73/.  The error appears to be a one-off thing, but since the follow-ups aren't stored we have no way of knowing what the actual data was.
Also, in the event of an error, it would be helpful to resend the data to make sure the user gets subscribed as desired
=> Save follow ups in the database

public/xmlns/content.xsd
`text-style` is a token list, so multiple space-separate styles could be defined. currently we only define the `bold` style.
example text node:
```xml
<content:text text-style="bold">Bold Text</content:text>
<content:text text-style="italic underline">Underlined Italic text</content:text>
```
=> add support for defining text-style="bold"

public/xmlns/tract.xsd
Is optional, and must follow rbga(#,#,#,#) format. Colors only the button, not any descendent text elements
=> Add button-color attribute to callToAction element

Gemfile, Gemfile.lock
This repo is public so security vulnerabilities should be fixed ASAP.
=> Update nokogiri to fix vulnerability

Gemfile, Gemfile.lock, app/controllers/languages_controller.rb, app/models/language.rb, app/serializers/language_serializer.rb, app/validators/language_validator.rb, db/migrate/20180212221933_add_direction_to_languages.rb, db/schema.rb, spec/acceptance/languages_controller_spec.rb
Adds "direction" attribute to language. This attribute will help clients know which way text ought to be rendered for a given languages. Defaults to "ltr" unless otherwise specified.
endpoint validates values to be either: "ltr" and "rtl"
=> Gt 449 right to left attribute

public/xmlns/analytics.xsd, public/xmlns/content.xsd, public/xmlns/tract.xsd
This defines an `<analytics:event>` xml node for use within tract XML to define when & what analytics events to trigger for specific content interactions.
a sample of what this xml would be:
```xml
<card>
<label>
<content:text>Here is a suggested prayer</content:text>
</label>
<analytics:event action="KGP Gospel Presented" delay="5" system="adobe" trigger="visible">
<analytics:attribute key="cru.presentingthegospel" value="" />
</analytics:event>
</card>
<button>
<content:text>Button</content:text>
<analytics:event action="FourLaws Email Sign Up" system="adobe" trigger="selected">
<analytics:attribute key="cru.emailsignup" value="true" />
<analytics:attribute key="cru.emaillist" value="5" />
</analytics:event> …
```
=> RFC: Define Analytics events in tract XML

db/migrate/20180416210608_translations_tagline_drop_default.rb
updating all records with callbacks means that for every published translation, we call out to onesky and push to s3. this:
a) takes way too long
b) overwrites old version of pushed zips to s3. probably not a huge deal, but the versions are nice
=> Go back to update_all to avoid callbacks

public/xmlns/tract.xsd
Sample:
```xml
<hero>
<heading>
<content:text>Knowing God Personally</content:text>
</heading>
<analytics:event action="KGP Gospel Presented" delay="5" system="adobe" trigger="visible">
<analytics:attribute key="cru.presentingthegospel" value="" />
</analytics:event>
<content:paragraph>
</content:paragraph>
</hero>
```
=> support defining analytics events on page heroes

public/xmlns/analytics.xsd
This change will prevent analytics attributes from accidentally being repeated within a single event
=> attribute keys within a single analytics event should be unique

app/models/follow_up.rb, spec/models/follow_up_spec.rb
Pass access secret and id in URL as form data instead of as headers. Growthspaces was updated to handle them in this way.
Log response code for all requests
=> Debug follow up issue results

public/xmlns/content.xsd
This will allow us to display different images for web vs mobile. The main impetus for this is that we want to render a different inline image for the knowgod.com web UI.
In order for us to utilize this for the web we will need to update the mobile apps to ignore images that are restricted to web only. Because of this need for an update to our mobile apps we may need to dialog around this and figure out if there might be a better solution available.
Example:
```xml
<content:image resource="both1.png" />
<content:image resource="both2.png" restrictTo="mobile web" />
<content:image resource="mobileInline.png" restrictTo="mobile" />
<content:image resource="webInline.png" restrictTo="web" />
```
=> Allow images to be restricted to web or mobile devices only

lib/package.rb, lib/xml_util.rb, spec/package_spec.rb
I'm starting to refactor parts of the manifest/page xml generation process to better support some new manifest features in process. This is just a small correctness fix
=> when creating an empty manifest, utilize the correct namespace

public/xmlns/content.xsd
The theory behind this is to allow a user to click an image and have that trigger an active tab
=> [GT-509] allow images to trigger content events and for tabs to listen for them

db/seeds.rb, public/xmlns/article.xsd, public/xmlns/manifest.xsd, spec/acceptance/translated_pages_controller_spec.rb
Sample XML:
```xml
<pages>
<article:aem-import src="https://stage.cru.org/content/experience-fragments/questions_about_god/english" />
<article:aem-import src="https://stage.cru.org/content/experience-fragments/questions_about_god/english/about_god" />
</pages>
```
=> add xml support for importing AEM articles

.rubocop.yml, Gemfile, Gemfile.lock, app/controllers/custom_manifests_controller.rb, app/models/custom_manifest.rb, app/models/resource.rb, app/models/translation.rb, app/models/xml/manifest.rb, app/serializers/custom_manifest_serializer.rb, app/validators/xml_validator.rb, config/routes.rb, db/migrate/20190716115741_custom_manifests_per_language.rb, db/schema.rb, spec/acceptance/auth_controller_spec.rb, spec/acceptance/custom_manifests_controller_spec.rb, spec/acceptance/custom_pages_controller_spec.rb, spec/acceptance/follow_ups_controller_spec.rb, spec/acceptance/languages_controller_spec.rb, spec/acceptance/translated_attributes_controller_spec.rb, spec/acceptance/translated_pages_controller_spec.rb, spec/models/custom_manifest_spec.rb, spec/models/xml/manifest_spec.rb
a custom manifest might be set for a given language and resource
in that sense its unique - only one can exists for given (resource_id, language_id)
builds on top of [(GT-517)](https://github.com/CruGlobal/mobile-content-api/pull/179)
re-arranged routes (to skip some unused ones -> returned 404 will be the same) 
and moved gems under their proper development/test section
*NOTE: includes a commit from #179 (will rebase after its merged)*
=> GT-518: Support language specific manifests

app/controllers/custom_manifests_controller.rb, app/serializers/resource_serializer.rb, spec/acceptance/attributes_controller_spec.rb, spec/acceptance/custom_manifests_controller_spec.rb, spec/acceptance/custom_pages_controller_spec.rb, spec/acceptance/drafts_controller_spec.rb, spec/acceptance/languages_controller_spec.rb, spec/acceptance/pages_controller_spec.rb, spec/acceptance/resources_controller_spec.rb, spec/acceptance/translated_attributes_controller_spec.rb, spec/acceptance/translated_pages_controller_spec.rb, spec/acceptance_helper.rb
follow-up on #181 
really just: https://github.com/CruGlobal/mobile-content-api/compare/GT-518+include?expand=1#diff-032d1ef5aa2c930497d19dbe702d814cR15
but I keep finding surprises - acceptance tests were keeping the authorization header for the whole unit
=> export custom-manifests association on resource

app/controllers/application_controller.rb, app/controllers/resources_controller.rb, spec/controllers/application_controller_spec.rb
as currently **PUT /resources/1/onesky** *keep-existing-phrases=false*
will end up doing a `push_new_onesky_translation(keep_existing_phrases = true)`
=> [fix] do proper true/false param conversion

db/migrate/20200220150100_add_service_type_to_destination.rb, db/schema.rb, db/seeds.rb
This is the first of two PRs, the first one adds adobe related fields to the destinations table, allowing them to be filled up before deploying further changes (which will require this information).
https://jira.cru.org/browse/GT-698
=> GT-698: [step-1] Allow a GodTools user to sign up for content hosted in Adobe Campaigns

spec/rails_helper.rb
Cleaning (by rollback) was failing intermittently for one test file (spec/models/attachment_spec.rb) due, I assume, to interaction with the seed data.
Having the same db (and seed data) for all tests seems to work reliably even when test order is randomized.
=> Only clean the db after all tests

.travis.yml, public/xmlns/training.xsd, schema_tests/training/invalid/tests/tip_invalid_type.xml, schema_tests/training/valid/tests/tip_type.xml
In the figma design there are a few different "types" of tips. This XML schema change is to support defining the type of tip via xml.
Sample tip w/ type XML:
```xml
<tip xmlns="https://mobile-content-api.cru.org/xmlns/training" type="ask">
<pages />
</tip>
```
=> Define a training tip type

public/xmlns/tract.xsd, public/xmlns/training.xsd, schema_tests/tract/valid/tests/header_training_tip.xml
This PR makes it possible to specify a tip for a page header. example xml:
```xml
<page xmlns="https://mobile-content-api.cru.org/xmlns/tract"
xmlns:content="https://mobile-content-api.cru.org/xmlns/content"
xmlns:training="https://mobile-content-api.cru.org/xmlns/training">
<header training:tip="tip1">
<title><content:text>header</content:text></title>
</header>
</page>
```
=> GT-837 add support for attaching tips to a tract header

public/xmlns/content.xsd, schema_tests/tract/valid/tests/restrictTo.xml
This adds on the ability to further restrict content to only 1 mobile platform instead of both.
```xml
<content:button type="url" url="https://questions-about-god-deeplink.com" restrictTo="android" />
```
=> GT-941 make it possible to restrict content to android or ios exclusively

public/xmlns/content.xsd, schema_tests/tract/invalid/tests/minimumRendererVersion_not_an_int.xml, schema_tests/tract/valid/tests/fallback.xml, schema_tests/tract/valid/tests/fallback_paragraph.xml
`<content:fallback/>` nodes provide a mechanism to define fallback for content that may not be supported on a renderer or device. To provide backwards compatibility for older renderers we are also introducing a `fallback` attribute on a paragraph element that will tell the renderer to treat that paragraph as a `<content:fallback />` element instead.
This will render "Android" on `android` devices, "iOS" on `ios` devices, and "Unknown" on all other devices (e.g. web)
```xml
<content:fallback>
<content:text restrictTo="android">Android</content:text>
<content:text restrictTo="ios">iOS</content:text>
<content:text>Unknown</content:text>
</content:fallback>
```
The same example utilizing a `<content:paragraph />` element
```xml
<content:paragraph fallback="true">
<content:text …
```
=> GT-941 Fallback content spec

public/xmlns/content.xsd, schema_tests/tract/invalid/tests/minimumRendererVersion_not_an_int.xml, schema_tests/tract/valid/tests/fallback.xml
This is an adjustment to naming and schema organization for the new `version` fallback mechanism
=> rename minimumRendererVersion to be version

app/models/attachment.rb
It seems the the errors from the test suite and production differ, so this should fix the issue with uploading attachments.
=> Make sure to rescue from error in production

public/xmlns/content.xsd, public/xmlns/tract.xsd
This adds the ability to specify a button "style" that controls rendering.
```xml
<content:button style="outlined"><content:text>Close lesson</content:text></content:text>
<content:button style="outlined"><content:text>Replay lesson</content:text></content:text>
<content:button><content:text>Things to try</content:text></content:text>
```
other examples:
```xml
<content:button style="outlined" color="rgba(255,0,0,1)"><content:text>Red Button</content:text></content:button>
<content:button style="outlined" color="rgba(255,0,0,1)" background-color="rgba(0,0,255,0.2)"><content:text>Red outline w/ light-blue background</content:text></content:button>
```
=> GT-1054 add an outlined button style to the content spec

app/lib/package.rb, public/xmlns/content.xsd, schema_tests/tract/invalid/tests/text_start_image_size_negative.xml, schema_tests/tract/invalid/tests/text_start_image_size_zero.xml, schema_tests/tract/valid/tests/text_inline_images.xml
Sample xml:
```
<content:text start-image="image.png"><- Image should be here</content:text>
<content:text start-image="image.png" start-image-size="16"><- Image should be here</content:text>
<content:text end-image="image.png">Image should be here -></content:text>
<content:text end-image="image.png" end-image-size="16">Image should be here -></content:text>
```
=> GT-1030 Support start & end images on text nodes

app/validators/xml_validator.rb, spec/models/abstract_page_spec.rb
Previously the API would accept some badly formed XML.
For example, the following XML would be accepted as valid even though it didn't have a closing tag:
```xml
<page xmlns="https://mobile-content-api.cru.org">
```
=> GT-1081 enable strict XML validation

public/xmlns/manifest.xsd
```xml
<manifest xmlns="https://mobile-content-api.cru.org/xmlns/manifest" dismiss-listeners="event_name" />
```
=> GT-1106 support defining dismiss-listeners for manifests to close a tool

public/xmlns/lesson.xsd, public/xmlns/manifest.xsd, public/xmlns/tract.xsd, schema_tests/lesson/valid/tests/text_attrs.xml, schema_tests/manifest/valid/tests/text_attrs.xml, schema_tests/tract/valid/tests/text_styles.xml
Define text-scale attributes for the manifest, lesson pages, and tract pages. To calculate the final size of text content you would perform the following calculation:
`{text.textScale} * {page.textScale} * {manifest.textScale} * {base text_size}`
Samples
Manifest:
```xml
<manifest xmlns="https://mobile-content-api.cru.org/xmlns/manifest" text-scale="1.2345" />
```
Lesson Page:
```xml
<page xmlns="https://mobile-content-api.cru.org/xmlns/lesson" text-scale="1.2345">
<content />
</page>
```
Tract Page:
```xml
<page xmlns="https://mobile-content-api.cru.org/xmlns/tract" text-scale="1.2345" />
```
=> GT-1147 Add text-scale attribute to manifest and pages

.travis.yml, public/xmlns/content.xsd, public/xmlns/lesson.xsd, public/xmlns/training.xsd, schema_tests/lesson/invalid/tests/spacer_negative.xml, schema_tests/lesson/invalid/tests/spacer_paragraph.xml, schema_tests/lesson/invalid/tests/spacer_paragraph_auto.xml, schema_tests/lesson/valid/tests/spacers.xml
Examples:
Auto-sized spacers:
```xml
<content:spacer />
<content:spacer mode="auto" />
```
Fixed-size spacers:
```xml
<content:spacer mode="fixed" height="40" />
```
=> GT-1148 Support a fixed height mode for the content spacer

app/models/language_attribute.rb, spec/acceptance/resource_languages_controller_spec.rb, spec/models/language_attribute_spec.rb
resource-language attributes should be unique in the context of a `{resource}-{language}-{key}` composite key.
Before this change we couldn't use the same resource-language key on multiple languages for a resource.
=> GT-1200 Resource language uniqueness

app/models/attachment.rb, config/environments/development.rb
I tried `rails db:seed` today and had two issues:
- downloading attachements by url doesn't connect (no local server running)
- uploading "attachments" failed because it tried going to s3
=> some dev setup improvements

public/xmlns/content.xsd, public/xmlns/lesson.xsd, public/xmlns/manifest.xsd, schema_tests/lesson/invalid/tests/multiselect_duplicate_option_value.xml, schema_tests/lesson/valid/tests/multiselect.xml
This adds XML support for a Multiselect element, state, and eventId support for utilizing state.
TODO:
Examples:
```xml
<content:multiselect state="quiz1" selection-limit="1">
<content:option value="answer1" selected-color="rgba(200,255,200,1)">
<content:text>Answer 1</content:text>
</content:option>
<content:option value="answer2">
<content:text>Answer 2</content:text>
</content:option>
<content:option value="answer3" background-color="rgba(255,255,255,1)">
<content:text>Answer 3</content:text>
</content:option>
</content:multiselect>
```
```xml
<content:button type="event" event="state:quiz1" />
```
=> GT-1180 Create a multi-select content element

public/xmlns/content.xsd
This attribute will allow us to only show certain content elements when other content elements are supported by the renderer.
Example:
```xml
<content:fallback>
<content:paragraph version="2" required-features="multiselect">
<content:multiselect>
<content:option><content:text>Answer 1</content:text></content:option>
<content:option><content:text>Answer 2</content:text></content:option>
</content:multiselect>
<content:button><content:text>Check Answer</content:text></content:button>
</content:paragraph>
<content:paragraph>
<content:button><content:text>Answer 1</content:text></content:button>
<content:button><content:text>Answer 2</content:text></content:button>
</content:paragraph>
</content:fallback>
```
=> add support for a requiredFeatures content restriction

app/lib/package.rb, public/xmlns/content.xsd
This allows an icon to be defined for a button which will be rendered inside the button.
Example:
```xml
<content:button type="url" icon="globe.png" icon-size="18" icon-gravity="end">
<content:text>Website</content:text>
</content:button>
```
=> GT-1235 Add support for defining icons in buttons

public/xmlns/content.xsd
This changes allows elements to dynamically be visible in a UI.
examples:
```xml
<content:button invisible-if="values(quiz1) >= 1" />
<content:button hidden-if="!isSet(quiz1)" />
```
=> GT-1232 add support for `invisible-if` and `hidden-if` attributes on content elements

public/xmlns/lesson.xsd, schema_tests/lesson/valid/tests/analytics_events.xml
Sample XML:
```xml
<page xmlns="https://mobile-content-api.cru.org/xmlns/lesson" xmlns:analytics="https://mobile-content-api.cru.org/xmlns/analytics">
<analytics:event system="appsflyer" />
<content />
</page>
```
=> GT-1278 Add analytics events to lesson pages

public/xmlns/analytics.xsd, public/xmlns/content.xsd
In the long term selected may get reused for more targetted events on multiselect options
=> GT-1272 Adjust AnalyticsEvent trigger values

public/xmlns/content.xsd, schema_tests/tract/invalid/tests/button_missing_text.xml, schema_tests/tract/valid/tests/button_analytics.xml, schema_tests/tract/valid/tests/links.xml
This is mostly code cleanup to make the spec a little more robust & flexible.
Functional changes:
- Allow analytics events to be defined before the text in buttons and links
- Add url attributes to link content element to make it possible to open urls from links
- Add base attributes (`restrictTo`, `version`, `required-features`) to link element
- Tighten up attributes allowed on the `content:text` child of a link. It's no longer possible to set start/end images on this element.
=> GT-980 Standardize "clickable" elements within the content spec

public/xmlns/content.xsd, public/xmlns/lesson.xsd, public/xmlns/manifest.xsd, public/xmlns/tract.xsd
- simplify listeners type
- rename content:events type
- consolidate textStyles attribute
- consolidate the deviceTypes type
- consolidate the features type
=> Content Spec cleanup

public/xmlns/content.xsd
Use the clickable attributeGroup on Images and Animations for consistency. This same attributeGroup will be used by content Cards
=> GT-1339 Make Animations and Images "clickable"

public/xmlns/content.xsd
Support defining a pixel width and horizontal gravity for images and buttons.
Examples:
```xml
<content:button url="https://example.com" width="150" gravity="end">
<content:text>Button</content:text>
</content:button>
```
```xml
<content:image resource="image.png" width="64" gravity="center" />
```
=> GT-1291 Support setting pixel width for images

app/models/user_counter.rb, spec/models/user_counter_spec.rb
This adds a validation to user counter names to reject any names that don't use URI safe characters
=> restrict valid characters for user counter names

app/models/xml/translatable.rb, db/seeds.rb, spec/models/translation_spec.rb
set the parent element's child element instead of simply updating the
url-i18n-id element
=> fix potential duplicate attributes on translation substitutions

config/routes.rb, spec/acceptance/user_counters_controller_spec.rb
As we are starting to flesh out more user related APIs, I want to organize all user endpoints under: `/user/me` with a future potential url pattern of `/user/:user_id` to run the APIs against other users.
I kept a copy of the update route at the old location for old versions of the GodTools Android app
=> GT-1776 move the user counters API to /user/me/counters

public/xmlns/content.xsd, schema_tests/content/invalid/tests/text_required_android_version_invalid.xml, schema_tests/content/invalid/tests/text_required_ios_version_invalid.xml, schema_tests/content/valid/tests/text_required_versions.xml
```xml
<content:text required-android-version="6.0.1" />
<content:text required-ios-version="6.0.0" />
<content:text required-android-version="6.0.0" required-ios-version="5.9.0" />
```
=> GT-1569 Add support for a required-android-version and required-ios-version property on content elements

public/xmlns/content.xsd, schema_tests/tract/valid/tests/content_required_device_type.xml
- rename restrictTo to required-device-type to match pattern of other content restriction attributes
- fix a typo in required-ios-version documentation
- add a test for the newly renamed required-device-type attribute
=> GT-1569 Rename restrictTo to require-device-type

.github/workflows/ruby.yml
Codecov can resolve public GHA builds without needing a explicit token, but they accomplish this by using a shared github token that regularly hits rate limits.
to work around this the recommendation is to configure a `CODECOV_TOKEN` which allows codecov to utilize a separate github token associated with our codecov account that has separate rate limit tracking.
=> Add CODECOV_TOKEN to avoid public API rate limits

Gemfile, Gemfile.lock
redis 5.0 is currently not supported by the actioncable pubsub adapter.
=> Downgrade redis

public/xmlns/content.xsd
6.0.3 of iOS included v0.7.0 of the shared parser, which added `required-device-types` and `required-versions` support
=> Update supported app versions

public/xmlns/analytics.xsd
We no longer use snowplow, so we don't need to support parsing snowplow analytics events
=> GT-1858 remove Snowplow analytics system

app/serializers/resource_serializer.rb, db/seeds.rb, spec/acceptance/resources_controller_spec.rb
without this, using `include=default-variant` doesn't include the relationship
=> GT-1939 add the appropriate key to the `default_variant` serializer relationship

public/xmlns/analytics.xsd
Adds `id` & `limit` attributes to analytics events. The `limit` attribute defines how many times an event could be fired, the `id` is used to track if the analytics event has already been fired.
```
<analytics:event id="completion_event" action="lessondemonstrate_complete" system="appsflyer firebase" limit="1" />
<analytics:event id="user_completion_event" action="lesson_completions.lessondemonstrate" system="user" limit="1" />
```
=> GT-1909 limit the number of times an analytics event can be fired

public/xmlns/analytics.xsd, schema_tests/lesson/valid/lessongs/01_title.xml, schema_tests/lesson/valid/tests/analytics_events.xml, schema_tests/tract/valid/kgp/07_AttitudeOfYourHeart.xml, schema_tests/tract/valid/tests/hero_analytics.xml
@aaronlaib I'm removing the AppsFlyer analytics system due to us no longer using AppsFlyer. This won't break existing tools, but will prevent you from saving updates to a page that contain AppsFlyer analytics events.
=> Remove the AppsFlyer analytics system from the content spec

app/lib/xml_util.rb, app/models/translation.rb, app/models/xml/filterable.rb, app/models/xml/manifest.rb, public/xmlns/article.xsd, public/xmlns/content.xsd, public/xmlns/manifest.xsd, public/xmlns/publish.xsd, schema_tests/content/valid/tests/publish_filtering.xml, schema_tests/manifest/invalid/tests/category_missing_label.xml, schema_tests/manifest/invalid/tests/category_publish_filtering_label.xml, schema_tests/manifest/invalid/tests/locale-lang.xml, schema_tests/manifest/invalid/tests/locale-x.xml, schema_tests/manifest/valid/tests/locale-en.xml, schema_tests/manifest/valid/tests/locale-fr-CA.xml, schema_tests/manifest/valid/tests/locale-pap.xml, schema_tests/manifest/valid/tests/locale-ru-143.xml, schema_tests/manifest/valid/tests/locale-zh-Hant.xml, schema_tests/manifest/valid/tests/publish_filtering.xml, spec/models/xml/manifest_spec.rb
This PR adds support for a new `publish:if-locale="en"` and `publish:if-locale-not="en"` attributes that will filter published XML based on if you are publishing in the corresponding locale.
Sample XML:
```xml
<page
xmlns:content="https://mobile-content-api.cru.org/xmlns/content"
xmlns:publish="https://mobile-content-api.cru.org/xmlns/publish">
<content:paragraph publish:if-locale="en">
</content:paragraph>
<content:paragraph publish:if-locale-not="en">
</content:paragraph>
</page>
```
=> GT-2261 Support new xml filtering directives in the manifest and content xml

public/xmlns/content.xsd, public/xmlns/cyoa.xsd, public/xmlns/cyoa_pages.xsd, public/xmlns/page.xsd, public/xmlns/page_base.xsd, public/xmlns/page_page-collection.xsd, schema_tests/cyoa/invalid/tests/page_page-collection_missing_page_type.xml, schema_tests/cyoa/invalid/tests/page_page-collection_no_pages.xml, schema_tests/cyoa/valid/tests/page_content_parent_path.xml, schema_tests/cyoa/valid/tests/page_page-collection.xml
new XML:
page collection page
```xml
<page xmlns="https://mobile-content-api.cru.org/xmlns/page"
xmlns:analytics="https://mobile-content-api.cru.org/xmlns/analytics"
xmlns:content="https://mobile-content-api.cru.org/xmlns/content"
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:type="page-collection" id="RG_page_collection">
<analytics:event action="test" system="firebase" />
<pages>
<import filename="Gifts01.json" />
<import filename="Gifts02.json" />
<import filename="Gifts03.json" />
<page xsi:type="content" id="embedded_page">
<analytics:event action="test" system="firebase" />
<content>
<content:spacer />
<content:paragraph>
<content:text>Text</content:text>
</content:paragraph>
</content>
</page> …
```
=> GT-2290 Support a pagecollection page type

public/xmlns/content.xsd, public/xmlns/web.xsd, schema_tests/content/valid/tests/flow_mixed_items.xml
```xml
<content:flow width="50%" web:width="25%" row-gravity="start" web:row-gravity="center">
<content:item width="15" web:width="30" />
</content:flow>
```
=> GT-2535 Create web overrides for flow item width and row gravity

public/xmlns/page_cardcollection.xsd, schema_tests/cyoa/valid/tests/page_cardcollection_header.xml
Sample page xml with a `<header>`: https://github.com/CruGlobal/mobile-content-api/pull/1779/files#diff-f687a435fce01c99755d1dac83f409892691c6487e39fc96060df8b3fd76111a
We support a full content stack in the header element, but be cautious adding too much content to the header
=> GT-2573 add an optional header to card collection pages

app/controllers/monitors_controller.rb
- Skip database connection checks in staging environment for /monitors/lb
endpoint
- Prepares staging environment for upcoming [Neon](https://neon.com/) database migration
- Will allow Neon to scale to zero during periods of inactivity by
preventing ALB health checks from keeping database connections active
=> Skip database connection in staging for /monitors/lb endpoint

config/environments/test.rb
tests have been really flaky since the rails 7.1 upgrade, setting the active_job queue adapter to the test adapter seems to fix the issues from my limited local testing replaying a test seed that would pretty consistently fail for me before the config change.
see: https://discuss.rubyonrails.org/t/activerecord-7-1-test-failures/83928/13
see: https://github.com/rails/rails/issues/46797
=> use the test active_job queue adapter
